[project]
name = "expensetracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "authlib>=1.3.2",
    "fastapi[all]>=0.116.1",
    "google-genai>=1.28.0",
    "httpx>=0.28.1",
    "pytest>=8.4.1",
    "python-dotenv>=1.1.1",
    "streamlit>=1.47.1",
    "streamlit-image-button>=0.2.2.13",
    "uvicorn>=0.35.0",
]
